name: Bump ComplxCulture

on:
  schedule:
    - cron: "30 1,3,5,7,9,11,13,15,17,19,21,23 * * *"
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install aiohttp
      - name: Bump ComplxCulture
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          GUILD_ID: "1267422282134061129"
          CHANNEL_ID: "1367544832360317020"
          SERVER_NAME: "ComplxCulture"
        run: python bump.py
